version: "3.8"

services:
  postgres:
    image: postgres
    container_name: quick-postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: quick-redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: quick-localstack
    environment:
      - SERVICES=sqs,sns
    ports:
      - "4566:4566"
    extra_hosts:
      - "host.docker.internal:host-gateway"
